### ISSUE TITLE
As a developer, I want to start the server using Docker

### ISSUE THREAD

**Issue by laurent-lao** [SOEN-390-Team-20/Team-20-SOEN-390#1]
As a developer, I want to be able to start the webapp servers using Docker, so that I can easily deploy them on any machine I wish.

Definition of Done:
- [x] Back-end can be launched in development environment with docker-compose
- [x] Back-end can be launched in production environment with docker-compose
- [x] Changes to back-end in development environment do not require a rebuild (nodemon)
- [x] Front-end can be launched in development environment with docker-compose
- [x] Front-end can be launched in production environment with docker-compose
- [x] Changes to front-end in development environment do not require a rebuild (nodemon)
- [x] Back-end and front-end can be launched simultaneously in development environment with docker-compose
- [x] Back-end and front-end can be launched simultaneously in production environment with docker-compose
- [x] Front-end can communicate with Back-end
- [x] Generate usage documentation

Acceptance Test:
- [x] docker-compose up command works on two separate pc (the dev/first one from the [README.md](https://github.com/SOEN-390-Team-20/SOEN-390/blob/issue-1-docker/README.md))
- [x] Going to `localhost:3000` gives console event: `Console.log("respond with a resource")`
- [x] Going to `localhost:3001` displays Hello World
- [x] #7
- [x] Modifying `./frontend/src/App.js` (inside the `<p></p>`) changes `localhost:3000` without browser reload

**Comment by laurent-lao** [comment]
Deployment diagram updated.

**Comment by jacobmathewlopez** [comment]
- On windows, docker-compose on the project directory starts up the backend but frontend does not load. Need to cd to both directories and docker-compose to load frontend.
- When both containers run, altering backend "Hello World" does not reload backend changes on browser refresh. Need to stop and restart docker container to see changes
- When both containers run, altering <p></p> phrase does not reload frontend changes even on browser refresh. Need to stop and restart docker container to see changes

**Comment by jacobmathewlopez** [comment]
Issue fixed: For windows user, Docker has trouble running both containers from root directory. To run project on windows, open 2 terminals:

**BACKEND**
1.  In the first terminal: `cd backend`, `npm install`, `npm run dev`

**FRONTEND**
2. In the second terminal: `cd frontend`, `npm install`, `npm start`

**Notes**
- npm install only need to do once, or if dependencies have updated
- Can use  `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build` in either directory to use docker containers, this will take some time and install dependencies automatically BUT will not allow hot-reloading.
