### ISSUE TITLE
Design and create the patient dashboard menu bar component

### ISSUE THREAD

**Issue by hubjongit** [SOEN-390-Team-20/Team-20-SOEN-390#37]
**USER STORY: #29**

Refer to user story #29 for menu items to be added.

Look at the style GitHub has for nav/menu bar for repositories where they use TABS to separate dashboard section — use as inspiration.
Can also be made as a left sidebar.
Feel free to discuss with team on how to design/implement

**Comment by laurent-lao** [comment]
#107 closed this
